package org.alex73.fanetyka.impl;

public class Fanetyka {
    public static String mark(String fanetyka, String beg, String end) {
        boolean found = false;
        for (int i = 0; i < fanetyka.length(); i++) {
            char c = fanetyka.charAt(i);
            if (Fanetyka.isLitara(c)) {
                fanetyka = fanetyka.substring(0, i) + beg + c + end + fanetyka.substring(i + 1);
                i += beg.length() + end.length();
                found = true;
            }
        }
        return found ? fanetyka : null;
    }

    public static boolean isLitara(char c) {
        return "йцкнгшўзхфвпрлджчсмтбёуеыаоэяію'’ьЙЦКНГШЎЗХФВПРЛДЖЧСМТБЁУЕЫАОЭЯІЮЬ".indexOf(c) >= 0;
    }

    public static String fanetykaSlova(String slova) {
        slova = slova.replaceAll("бе", "bʲɛ");
        slova = slova.replaceAll("бё", "bʲɔ");
        slova = slova.replaceAll("бі", "bʲi");
        slova = slova.replaceAll("бю", "bʲu");
        slova = slova.replaceAll("бя", "bʲa");
        slova = slova.replaceAll("мве", "ɱvʲɛ");
        slova = slova.replaceAll("мвё", "ɱvʲɔ");
        slova = slova.replaceAll("мві", "ɱvʲi");
        slova = slova.replaceAll("мвю", "ɱvʲu");
        slova = slova.replaceAll("мвя", "ɱvʲa");
        slova = slova.replaceAll("мфе", "ɱfʲɛ");
        slova = slova.replaceAll("мфё", "ɱfʲɔ");
        slova = slova.replaceAll("мфі", "ɱfʲi");
        slova = slova.replaceAll("мфю", "ɱfʲu");
        slova = slova.replaceAll("мфя", "ɱfʲa");
        slova = slova.replaceAll("ве", "vʲɛ");
        slova = slova.replaceAll("вё", "βʲɔ");
        slova = slova.replaceAll("ві", "vʲi");
        slova = slova.replaceAll("вю", "βʲu");
        slova = slova.replaceAll("вя", "vʲa");
        slova = slova.replaceAll("ге", "ʝɛ");
        slova = slova.replaceAll("гё", "ʝɔ");
        slova = slova.replaceAll("гі", "ʝi");
        slova = slova.replaceAll("гю", "ʝu");
        slova = slova.replaceAll("гя", "ʝa");
        slova = slova.replaceAll("ддзе", "d͡zʲːɛ");
        slova = slova.replaceAll("ддзё", "d͡zʲːɔ");
        slova = slova.replaceAll("ддзі", "d͡zʲːi");
        slova = slova.replaceAll("ддзю", "d͡zʲːu");
        slova = slova.replaceAll("ддзя", "d͡zʲːa");
        slova = slova.replaceAll("дзе", "d͡zʲɛ");
        slova = slova.replaceAll("дзё", "d͡zʲɔ");
        slova = slova.replaceAll("дзі", "d͡zʲi");
        slova = slova.replaceAll("дзю", "d͡zʲu");
        slova = slova.replaceAll("дзя", "d͡zʲa");
        slova = slova.replaceAll("ззе", "zʲːɛ");
        slova = slova.replaceAll("ззё", "zʲːɔ");
        slova = slova.replaceAll("ззі", "zʲːi");
        slova = slova.replaceAll("ззю", "zʲːu");
        slova = slova.replaceAll("ззя", "zʲːa");
        slova = slova.replaceAll("зе", "zʲɛ");
        slova = slova.replaceAll("зё", "zʲɔ");
        slova = slova.replaceAll("зі", "zʲi");
        slova = slova.replaceAll("зю", "zʲu");
        slova = slova.replaceAll("зя", "zʲa");
        slova = slova.replaceAll("ке", "cɛ");
        slova = slova.replaceAll("кё", "cɔ");
        slova = slova.replaceAll("кі", "ci");
        slova = slova.replaceAll("кю", "cu");
        slova = slova.replaceAll("кя", "ca");
        slova = slova.replaceAll("лле", "ʎːɛ");
        slova = slova.replaceAll("ллё", "ʎːɔ");
        slova = slova.replaceAll("ллі", "ʎːi");
        slova = slova.replaceAll("ллю", "ʎːu");
        slova = slova.replaceAll("лля", "ʎːa");
        slova = slova.replaceAll("ле", "ʎɛ");
        slova = slova.replaceAll("лё", "ʎɔ");
        slova = slova.replaceAll("лі", "ʎi");
        slova = slova.replaceAll("лю", "ʎu");
        slova = slova.replaceAll("ля", "ʎa");
        slova = slova.replaceAll("ме", "mʲɛ");
        slova = slova.replaceAll("мё", "mʲɔ");
        slova = slova.replaceAll("мі", "mʲi");
        slova = slova.replaceAll("мю", "mʲu");
        slova = slova.replaceAll("мя", "mʲa");
        slova = slova.replaceAll("нне", "ɲːɛ");
        slova = slova.replaceAll("ннё", "ɲːɔ");
        slova = slova.replaceAll("нні", "ɲːi");
        slova = slova.replaceAll("нню", "ɲːu");
        slova = slova.replaceAll("ння", "ɲːa");
        slova = slova.replaceAll("не", "ɲɛ");
        slova = slova.replaceAll("нё", "ɲɔ");
        slova = slova.replaceAll("ні", "ɲi");
        slova = slova.replaceAll("ню", "ɲu");
        slova = slova.replaceAll("ня", "ɲa");
        slova = slova.replaceAll("пе", "pʲɛ");
        slova = slova.replaceAll("пё", "pʲɔ");
        slova = slova.replaceAll("пі", "pʲi");
        slova = slova.replaceAll("пю", "pʲu");
        slova = slova.replaceAll("пя", "pʲa");
        slova = slova.replaceAll("ссе", "sʲːɛ");
        slova = slova.replaceAll("ссё", "sʲːɔ");
        slova = slova.replaceAll("ссі", "sʲːi");
        slova = slova.replaceAll("ссю", "sʲːu");
        slova = slova.replaceAll("сся", "sʲːa");
        slova = slova.replaceAll("се", "sʲɛ");
        slova = slova.replaceAll("сё", "sʲɔ");
        slova = slova.replaceAll("сі", "sʲi");
        slova = slova.replaceAll("сю", "sʲu");
        slova = slova.replaceAll("ся", "sʲa");
        slova = slova.replaceAll("фе", "fʲɛ");
        slova = slova.replaceAll("фё", "fʲɔ");
        slova = slova.replaceAll("фі", "fʲi");
        slova = slova.replaceAll("фю", "fʲu");
        slova = slova.replaceAll("фя", "fʲa");
        slova = slova.replaceAll("хе", "çɛ");
        slova = slova.replaceAll("хё", "çɔ");
        slova = slova.replaceAll("хі", "çi");
        slova = slova.replaceAll("хю", "çu");
        slova = slova.replaceAll("хя", "ça");
        slova = slova.replaceAll("цце", "t͡sʲːɛ");
        slova = slova.replaceAll("ццё", "t͡sʲːɔ");
        slova = slova.replaceAll("цці", "t͡sʲːi");
        slova = slova.replaceAll("ццю", "t͡sʲːu");
        slova = slova.replaceAll("цця", "t͡sʲːa");
        slova = slova.replaceAll("це", "t͡sʲɛ");
        slova = slova.replaceAll("цё", "t͡sʲɔ");
        slova = slova.replaceAll("ці", "t͡sʲi");
        slova = slova.replaceAll("цю", "t͡sʲu");
        slova = slova.replaceAll("ця", "t͡sʲa");
        slova = slova.replaceAll("дзь", "d͡zʲ");
        slova = slova.replaceAll("дd͡zʲ", "d͡zʲː");
        slova = slova.replaceAll("зь", "zʲ");
        slova = slova.replaceAll("ль", "ʎ");
        slova = slova.replaceAll("нь", "ɲ");
        slova = slova.replaceAll("сь", "sʲ");
        slova = slova.replaceAll("ць", "t͡sʲ");
        slova = slova.replaceAll("сbʲ", "zʲbʲ");
        slova = slova.replaceAll("сvʲ", "sʲvʲ");
        slova = slova.replaceAll("сd͡zʲ", "zʲd͡zʲ");
        slova = slova.replaceAll("сzʲ", "zʲː");
        slova = slova.replaceAll("сʎ", "sʲʎ");
        slova = slova.replaceAll("сmʲ", "sʲmʲ");
        slova = slova.replaceAll("сɲ", "sʲɲ");
        slova = slova.replaceAll("сpʲ", "sʲpʲ");
        slova = slova.replaceAll("сsʲ", "sʲː");
        slova = slova.replaceAll("сfʲ", "sʲfʲ");
        slova = slova.replaceAll("сt͡sʲ", "sʲt͡sʲ");
        slova = slova.replaceAll("зbʲ", "zʲbʲ");
        slova = slova.replaceAll("зvʲ", "zʲvʲ");
        slova = slova.replaceAll("зd͡zʲ", "zʲd͡zʲ");
        slova = slova.replaceAll("зzʲ", "zʲː");
        slova = slova.replaceAll("зʎ", "zʲʎ");
        slova = slova.replaceAll("зmʲ", "zʲmʲ");
        slova = slova.replaceAll("зɲʲ", "zʲɲʲ");
        slova = slova.replaceAll("зt͡sʲ", "sʲt͡sʲ");
        slova = slova.replaceAll("цvʲ", "t͡sʲvʲ");
        slova = slova.replaceAll("дзvʲ", "d͡zʲvʲ");
        slova = slova.replaceAll("кcʲ", "cʲː");
        slova = slova.replaceAll("kz", "gz");
        slova = slova.replaceAll("mf", "ɱf");
        slova = slova.replaceAll("’я", "ja");
        slova = slova.replaceAll("’е", "jɛ");
        slova = slova.replaceAll("’ё", "jɔ");
        slova = slova.replaceAll("’ю", "ju");
        slova = slova.replaceAll("д$", "t");
        slova = slova.replaceAll("ж$", "ʂ");
        slova = slova.replaceAll("з$", "s");
        slova = slova.replaceAll("б$", "p");
        slova = slova.replaceAll("г$", "x");
        slova = slova.replaceAll("дж$", "t͡ʂ");
        slova = slova.replaceAll("дзь$", "t͡sʲ");
        slova = slova.replaceAll("зь$", "sʲ");
        slova = slova.replaceAll("здч", "ʂt͡ʂ");
        slova = slova.replaceAll("ждж", "ʐd͡ʐ");
        slova = slova.replaceAll("здж", "ʐd͡ʐ");
        slova = slova.replaceAll("жк", "ʂk");
        slova = slova.replaceAll("зж", "ʐː");
        slova = slova.replaceAll("зш", "ʂː");
        slova = slova.replaceAll("сш", "ʂː");
        slova = slova.replaceAll("зч", "ʂt͡ʂ");
        slova = slova.replaceAll("сч", "ʂt͡ʂ");
        slova = slova.replaceAll("жч", "ʂt͡ʂ");
        slova = slova.replaceAll("дч", "t͡ʂː");
        slova = slova.replaceAll("тч", "t͡ʂː");
        slova = slova.replaceAll("дт", "tː");
        slova = slova.replaceAll("гк", "xk");
        slova = slova.replaceAll("гч", "xt͡ʂ");
        slova = slova.replaceAll("дц", "t͡sː");
        slova = slova.replaceAll("тц", "t͡sː");
        slova = slova.replaceAll("чц", "t͡sː");
        slova = slova.replaceAll("цц", "t͡sː");
        slova = slova.replaceAll("жж", "ʐː");
        slova = slova.replaceAll("шш", "ʂː");
        slova = slova.replaceAll("чч", "t͡ʂː");
        slova = slova.replaceAll("нн", "nː");
        slova = slova.replaceAll("а", "a");
        slova = slova.replaceAll("о", "ɔ");
        slova = slova.replaceAll("й", "j");
        slova = slova.replaceAll("у", "u");
        slova = slova.replaceAll("ы", "ɨ");
        slova = slova.replaceAll("э", "ɛ");
        slova = slova.replaceAll("шч", "ʂt͡ʂ");
        slova = slova.replaceAll("дж", "d͡ʐ");
        slova = slova.replaceAll("дз", "d͡z");
        slova = slova.replaceAll("aдс", "at͡s");
        slova = slova.replaceAll("aдsʲ", "at͡sʲsʲ");
        slova = slova.replaceAll("aдt͡sʲ", "at͡sʲː");
        slova = slova.replaceAll("дск", "t͡sk");
        slova = slova.replaceAll("дсc", "t͡sc");
        slova = slova.replaceAll("дст", "t͡st");
        slova = slova.replaceAll("тсc", "t͡sc");
        slova = slova.replaceAll("тск", "t͡sk");
        slova = slova.replaceAll("тст", "t͡st");
        slova = slova.replaceAll("я", "ja");
        slova = slova.replaceAll("р", "r");
        slova = slova.replaceAll("г", "ɣ");
        slova = slova.replaceAll("вɔ", "βɔ");
        slova = slova.replaceAll("вu", "βu");
        slova = slova.replaceAll("ств", "stv");
        slova = slova.replaceAll("зв", "zv");
        slova = slova.replaceAll("зк", "sk");
        slova = slova.replaceAll("дк", "tk");
        slova = slova.replaceAll("чн", "t͡ʂn");
        slova = slova.replaceAll("нк", "nk");
        slova = slova.replaceAll("зн", "zn");
        slova = slova.replaceAll("с$", "s");
        slova = slova.replaceAll("к", "k");
        slova = slova.replaceAll("п", "p");
        slova = slova.replaceAll("т", "t");
        slova = slova.replaceAll("х", "x");
        slova = slova.replaceAll("ц", "t͡s");
        slova = slova.replaceAll("ч", "t͡ʂ");
        slova = slova.replaceAll("ш", "ʂ");
        slova = slova.replaceAll("л", "l");
        slova = slova.replaceAll("ь", "j");
        slova = slova.replaceAll("н", "n");
        slova = slova.replaceAll("ф", "f");
        slova = slova.replaceAll("d͡zʲ$", "t͡sʲ");
        slova = slova.replaceAll("d͡ʐ$", "t͡ʂ");
        slova = slova.replaceAll("ў", "u̯");
        slova = slova.replaceAll("сl", "sl");
        slova = slova.replaceAll("зɲ", "zʲɲ");
        slova = slova.replaceAll("вɨ", "vɨ");
        slova = slova.replaceAll("б", "b");
        slova = slova.replaceAll("с", "s");
        slova = slova.replaceAll("м", "m");
        slova = slova.replaceAll("ж", "ʐ");
        slova = slova.replaceAll("д", "d");
        slova = slova.replaceAll("ё", "jɔ");
        slova = slova.replaceAll("з", "z");
        slova = slova.replaceAll("в", "v");
        slova = slova.replaceAll("е", "jɛ");

        slova = slova.replaceAll("^antɨі", "antɨi");
        slova = slova.replaceAll("^au̯taі", "au̯tai");
        slova = slova.replaceAll("^vɨsɔkaі", "vɨsɔkai");
        slova = slova.replaceAll("^ʝipʲɛrі", "ʝipʲɛrɨ");
        slova = slova.replaceAll("^pa-і", "pai");

        slova = slova.replaceAll("b'j", "bj");
        slova = slova.replaceAll("d'j", "dj");
        slova = slova.replaceAll("p'j", "pj");
        slova = slova.replaceAll("r'j", "rj");
        slova = slova.replaceAll("z'j", "zj");
        slova = slova.replaceAll("v'j", "vj");
        slova = slova.replaceAll("x'j", "xj");

        slova = slova.replaceAll("b'і", "bji");
        slova = slova.replaceAll("r'і", "rji");

        slova = slova.replaceAll("aю", "aju");
        slova = slova.replaceAll("uю", "uju");
        slova = slova.replaceAll("ɔю", "ɔju");
        slova = slova.replaceAll("ɨю", "ɨju");

        slova = slova.replaceAll("aі", "aji");
        slova = slova.replaceAll("ɔі", "ɔji");
        slova = slova.replaceAll("uі", "uji");
        slova = slova.replaceAll("ɛі", "ɛji");

        slova = slova.replaceAll("d'ю", "dju");
        slova = slova.replaceAll("ɛ-ю", "ɛju");

        ////////////////////
        slova = slova.replaceAll("tі", "tɨ");
        slova = slova.replaceAll("dі", "dɨ");
        slova = slova.replaceAll("ʐі", "ʐɨ");
        slova = slova.replaceAll("d-і", "d-ɨ");
        slova = slova.replaceAll("t-і", "t-ɨ");

        slova = slova.replaceAll("іnʂa", "jіnʂa");
        slova = slova.replaceAll("mʲiʐі", "mʲiʐɨ");
        slova = slova.replaceAll("v'юі", "vjuji");
        slova = slova.replaceAll("'ю", "ju");
        slova = slova.replaceAll("ю", "ju");

        slova = slova.replaceAll("^bʎit͡sʲi", "bʎit͡sɨ");
        slova = slova.replaceAll("^bʎit͡s-і", "bʎit͡s-ɨ");
        slova = slova.replaceAll("^unutrɨі", "unutrɨi");
        slova = slova.replaceAll("іnʂɨ", "jinʂɨ");
        slova = slova.replaceAll("іxɲi", "jixɲi");
        slova = slova.replaceAll("іxnɨ", "jixnɨ");
        slova = slova.replaceAll("ɲі", "ɲjі");
        slova = slova.replaceAll("z'і", "zji");
        slova = slova.replaceAll("ɨі", "ɨji");
        slova = slova.replaceAll("iі", "ii");

        slova = slova.replaceAll("a-і", "a-i");
        slova = slova.replaceAll("t-і", "t-ɨ");
        slova = slova.replaceAll("rі", "rɨ");

        slova = slova.replaceAll("ʐ'j", "ʐj");
        slova = slova.replaceAll("n'j", "nj");
        slova = slova.replaceAll("p'і", "pji");
        slova = slova.replaceAll("m'j", "mj");
        slova = slova.replaceAll("ʂ'j", "ʂj");
        slova = slova.replaceAll("k'j", "kj");
        slova = slova.replaceAll("f'j", "fj");
        slova = slova.replaceAll("t'j", "tj");

        slova = slova.replaceAll("tюx", "t͡sʲjux");

        slova = slova.replaceAll("і", "i");
        slova = slova.replaceAll("s'j", "sj");
        /////////////////
        slova = slova.replaceAll("bbʲ", "bʲː");
        slova = slova.replaceAll("bb", "bː");
        slova = slova.replaceAll("bt͡sʲ", "pt͡sʲ");
        slova = slova.replaceAll("mv", "ɱv");
        slova = slova.replaceAll("dc", "tc");
        slova = slova.replaceAll("zt", "st");
        slova = slova.replaceAll("zz", "zː");
        slova = slova.replaceAll("bk", "pk");
        slova = slova.replaceAll("bc", "pc");

        slova = slova.replaceAll("ʐc", "ʂc");
        slova = slova.replaceAll("bpʲ", "pʲː");
        slova = slova.replaceAll("bp", "pː");
        slova = slova.replaceAll("bsʲ", "psʲ");

        slova = slova.replaceAll("bs", "ps");
        slova = slova.replaceAll("bt", "pt");
        slova = slova.replaceAll("bx", "px");
        slova = slova.replaceAll("bt͡s", "pt͡s");

        slova = slova.replaceAll("bç", "pç");
        slova = slova.replaceAll("zdn", "zn");
        slova = slova.replaceAll("bʂ", "pʂ");
        slova = slova.replaceAll("ssʲ", "sʲː");
        slova = slova.replaceAll("ss", "sː");
        slova = slova.replaceAll("dd", "dː");

        slova = slova.replaceAll("stn", "sn");
        slova = slova.replaceAll("dp", "tp");
        slova = slova.replaceAll("df", "tf");
        slova = slova.replaceAll("dx", "tx");
        slova = slova.replaceAll("dʂ", "tʂ");
        slova = slova.replaceAll("kz", "gz");
        slova = slova.replaceAll("kd", "gd");
        slova = slova.replaceAll("zːʲ", "zʲː");
        slova = slova.replaceAll("zc", "sc");
        slova = slova.replaceAll("ʐsc", "sc");
        slova = slova.replaceAll("ɣc", "xc");

        slova = slova.replaceAll("dç", "tç");

        return slova;
    }
}
